Update track.py
CPBridge/pycrumbs pull request #1
Opened 2024-01-09 01:19 UTC by mccle

Add record chaining to `tracked` with the `chain_records` argument. If the `full_record_path` already exists, the previous record is read and the new record file will be appended to a list containing any previous records. If `full_record_path` does not exist, it works as normal. `chain_records` defaults to `False` with the assumption that most commands are not intended to continually add to the same directory / record over time.

2024-01-09 20:56 UTC, CPBridge commented on src/pycrumbs/track.py
> -        record_path = record_path.with_name(record_path.stem + '.json')
I see that you have added this functionality in the `tracked` function now, which is fine. But I would prefer to keep it here too (which should not break anything), as this is a public package and this change would represent a backward incompatible change to its behavior (this function is a public function)

2024-01-09 21:04 UTC, CPBridge requested changes
@mccle This is great, thanks!

This repo has some automated tests that are run using `pytest`. Could you perhaps add two simple test cases so that we can automate testing of this feature as new ones are added in the future? Test are [here](https://github.com/CPBridge/pycrumbs/blob/main/tests/test_track.py)

Specifically I'm thinking these two cases:
- `chain_records=True` when there is no existing record
- `chain_records=True` when there is an existing record

2024-01-09 22:48 UTC, mccle commented
@CPBridge I added these tests in `test_record_chaining`. I cover the cases where
* a record does not yet exist
* a record exists with one previous element
* a record exists and contains a list of 2+ elements

I also demonstrate that the elements at the beginning of the list remain unchained over time. I believe this should cover all of the use cases for using `chain_records` in `tracked`. Are there any other cases that should be considered?

2024-01-11 21:06 UTC, CPBridge commented
Perfect, thanks @mccle !

2024-01-11 21:06 UTC, CPBridge approved these changes

2024-01-11 21:06 UTC, merged